use nathank;

CREATE TABLE DEPARTMENTS(deptid INT PRIMARY KEY, dname TEXT, location TEXT);

CREATE TABLE FACULTY(fid INT PRIMARY KEY, fname TEXT, deptid INT, FOREIGN KEY(deptid) REFERENCES DEPARTMENTS(deptid));

CREATE TABLE STUDENT(snum INT PRIMARY KEY, sname TEXT, deptid INT, slevel TEXT, age INT, FOREIGN KEY (deptid) REFERENCES DEPARTMENTS(deptid));

CREATE TABLE CLASS(cname VARCHAR(255) PRIMARY KEY, meets_at TIME, room TEXT, fid INT);

CREATE TABLE ENROLLED(snum INT, cname VARCHAR(255), grade TEXT, PRIMARY KEY(snum, cname), FOREIGN KEY(snum) REFERENCES STUDENT(snum), FOREIGN KEY(cname) REFERENCES CLASS(cname));
